#!/usr/bin/env bash

get_state () {
  state=$(connmanctl technologies | sed '18!d' | awk '{print $3}')
  if [ $state = "True" ]; then
    echo on
  else
    echo off
  fi
}

turn_off () {
  connmanctl disable bluetooth 2>&1 > /dev/null
}

turn_on () {
  connmanctl enable bluetooth 2>&1 > /dev/null
}

toggle () {
  state=$(get_state)
  if [ $state = "True" ]; then
    turn_off
  else
    turn_on
  fi
}

if [ $1 = "state" ]; then
  get_state
fi

if [ $1 = "toggle" ]; then
  toggle
fi
