#!/bin/sh

toggle() {
    STATUS="$(bluetoothctl show | grep Powered | awk '{print $2}')"
    if [ $STATUS = "yes" ]; then
        rfkill block bluetooth
        notify-send -a "Bluetooth" --urgency=normal "Bluetooth" "Bluetooth has been turned off."
    else
        rfkill unblock bluetooth
        notify-send -a "Bluetooth" --urgency=normal "Bluetooth" "Bluetooth has been turned on."
    fi
}

if [ $1 = "--toggle" ]; then
        toggle
fi
