#!/bin/sh

STATUS=$(connmanctl technologies | grep Powered | sed '2!d' | awk '{print $3}')
SSID=$(iwgetid -r)
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

toggle() {
    if [ $STATUS = "True" ]; then
        connmanctl disable wifi
        notify-send -a "wifi"  --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
    else
        connmanctl enable wifi
        notify-send -a "wifi"  --urgency=normal "Wi-Fi" "Wi-Fi has been turned on!"
    fi
}


if [ $1 = "--toggle" ]; then
    toggle
fi
