---@diagnostic disable: undefined-global
require 'ui.notifications'
require 'ui.wallpaper'
require 'ui.menu'
-- require 'ui.titlebars'
require 'ui.bar'
require 'ui.systray'
require 'ui.dashboard'
-- require 'ui.notifcenter'
require 'ui.powermenu'
require 'ui.calendar'
-- require 'ui.dock'
require 'ui.music'
require 'ui.musicwidget'
-- require 'ui.lock'
require 'ui.control'
-- require 'ui.osd'
